language: ruby
before_install: "WITH_VERBOSE=1 script/with current bootstrap"
install: "WITH_VERBOSE=1 script/with current bundle install"
script: "WITH_VERBOSE=1 script/with current bundle exec rake test"
rvm:
  - 2.3.3
  - 2.4.2
  - 2.5.3
  - 2.6.2
  - jruby-9.1.17.0
  - jruby-9.2.7.0
gemfile:
  - test/gemfiles/Gemfile.ruby
  - test/gemfiles/Gemfile.rails-5.0.x
  - test/gemfiles/Gemfile.rails-5.2.x
  - test/gemfiles/Gemfile.rails-6.0.x
  - test/gemfiles/Gemfile.rails-6.1.x
matrix:
  exclude:
